# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 664)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setStyleSheet(".QPushButton[checkable=\"true\"]{\n"
"    border: none;\n"
"    min-width:100px;\n"
"    min-height:35px;\n"
"}\n"
".QPushButton[checked=\"true\"]{\n"
"    background:#aaaaaa;\n"
"}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnProjectTab = QtWidgets.QPushButton(self.groupBox_2)
        self.btnProjectTab.setStyleSheet("")
        self.btnProjectTab.setCheckable(True)
        self.btnProjectTab.setChecked(False)
        self.btnProjectTab.setAutoExclusive(True)
        self.btnProjectTab.setObjectName("btnProjectTab")
        self.gridLayout_2.addWidget(self.btnProjectTab, 1, 1, 1, 1)
        self.btnRunningTab = QtWidgets.QPushButton(self.groupBox_2)
        self.btnRunningTab.setCheckable(True)
        self.btnRunningTab.setAutoExclusive(True)
        self.btnRunningTab.setObjectName("btnRunningTab")
        self.gridLayout_2.addWidget(self.btnRunningTab, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 1, 1, 1)
        self.btnCustomTab = QtWidgets.QPushButton(self.groupBox_2)
        self.btnCustomTab.setCheckable(True)
        self.btnCustomTab.setAutoExclusive(True)
        self.btnCustomTab.setObjectName("btnCustomTab")
        self.gridLayout_2.addWidget(self.btnCustomTab, 3, 1, 1, 1)
        self.btnExportTab = QtWidgets.QPushButton(self.groupBox_2)
        self.btnExportTab.setCheckable(True)
        self.btnExportTab.setAutoExclusive(True)
        self.btnExportTab.setObjectName("btnExportTab")
        self.gridLayout_2.addWidget(self.btnExportTab, 4, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.tabProject = QtWidgets.QTabWidget()
        self.tabProject.setObjectName("tabProject")
        self.tab_30 = QtWidgets.QWidget()
        self.tab_30.setObjectName("tab_30")
        self.listWidget_2 = QtWidgets.QListWidget(self.tab_30)
        self.listWidget_2.setGeometry(QtCore.QRect(130, 270, 431, 191))
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.widget = QtWidgets.QWidget(self.tab_30)
        self.widget.setGeometry(QtCore.QRect(70, 20, 231, 211))
        self.widget.setObjectName("widget")
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setGeometry(QtCore.QRect(80, 10, 71, 61))
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap(":/img/spreadsheet_40px_573143_easyicon.net.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.btnJumpTemplate = QtWidgets.QPushButton(self.widget)
        self.btnJumpTemplate.setGeometry(QtCore.QRect(70, 176, 93, 28))
        self.btnJumpTemplate.setObjectName("btnJumpTemplate")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(60, 86, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setGeometry(QtCore.QRect(30, 136, 181, 20))
        self.label_21.setObjectName("label_21")
        self.widget_2 = QtWidgets.QWidget(self.tab_30)
        self.widget_2.setGeometry(QtCore.QRect(360, 20, 231, 211))
        self.widget_2.setObjectName("widget_2")
        self.label_45 = QtWidgets.QLabel(self.widget_2)
        self.label_45.setGeometry(QtCore.QRect(40, 136, 181, 20))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.widget_2)
        self.label_46.setGeometry(QtCore.QRect(50, 86, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_44 = QtWidgets.QLabel(self.widget_2)
        self.label_44.setGeometry(QtCore.QRect(70, 10, 71, 61))
        self.label_44.setText("")
        self.label_44.setPixmap(QtGui.QPixmap(":/img/doc_import_48px_14623_easyicon.net.png"))
        self.label_44.setScaledContents(True)
        self.label_44.setObjectName("label_44")
        self.btnJumpCutom = QtWidgets.QPushButton(self.widget_2)
        self.btnJumpCutom.setGeometry(QtCore.QRect(60, 176, 93, 28))
        self.btnJumpCutom.setObjectName("btnJumpCutom")
        self.tabProject.addTab(self.tab_30, "")
        self.tab_28 = QtWidgets.QWidget()
        self.tab_28.setObjectName("tab_28")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_28)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.cmbTagFilter = QtWidgets.QComboBox(self.tab_28)
        self.cmbTagFilter.setObjectName("cmbTagFilter")
        self.cmbTagFilter.addItem("")
        self.cmbTagFilter.addItem("")
        self.cmbTagFilter.addItem("")
        self.cmbTagFilter.addItem("")
        self.cmbTagFilter.addItem("")
        self.cmbTagFilter.addItem("")
        self.cmbTagFilter.addItem("")
        self.cmbTagFilter.addItem("")
        self.cmbTagFilter.addItem("")
        self.cmbTagFilter.addItem("")
        self.horizontalLayout_7.addWidget(self.cmbTagFilter)
        self.ledKeyword = QtWidgets.QLineEdit(self.tab_28)
        self.ledKeyword.setObjectName("ledKeyword")
        self.horizontalLayout_7.addWidget(self.ledKeyword)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.lbSpider = QtWidgets.QLabel(self.tab_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbSpider.sizePolicy().hasHeightForWidth())
        self.lbSpider.setSizePolicy(sizePolicy)
        self.lbSpider.setMinimumSize(QtCore.QSize(80, 0))
        self.lbSpider.setObjectName("lbSpider")
        self.horizontalLayout_5.addWidget(self.lbSpider)
        self.btnGotoTemplate = QtWidgets.QPushButton(self.tab_28)
        self.btnGotoTemplate.setObjectName("btnGotoTemplate")
        self.horizontalLayout_5.addWidget(self.btnGotoTemplate)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.tableWidget = QtWidgets.QTableWidget(self.tab_28)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout_7.addWidget(self.tableWidget)
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_71.setSpacing(6)
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_71.addItem(spacerItem3)
        self.btnNewSpider = QtWidgets.QPushButton(self.tab_28)
        self.btnNewSpider.setObjectName("btnNewSpider")
        self.horizontalLayout_71.addWidget(self.btnNewSpider)
        self.btnSaveSpiderTable = QtWidgets.QPushButton(self.tab_28)
        self.btnSaveSpiderTable.setObjectName("btnSaveSpiderTable")
        self.horizontalLayout_71.addWidget(self.btnSaveSpiderTable)
        self.verticalLayout_7.addLayout(self.horizontalLayout_71)
        self.tabProject.addTab(self.tab_28, "")
        self.tab_24 = QtWidgets.QWidget()
        self.tab_24.setObjectName("tab_24")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_24)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lbBaseurl = QtWidgets.QLabel(self.tab_24)
        self.lbBaseurl.setObjectName("lbBaseurl")
        self.gridLayout_5.addWidget(self.lbBaseurl, 2, 3, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_24)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_11.addWidget(self.lineEdit_9)
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_24)
        self.pushButton_3.setMaximumSize(QtCore.QSize(35, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_11.addWidget(self.pushButton_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.gridLayout_5.addLayout(self.horizontalLayout_11, 5, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.tab_24)
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.tab_24)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 4, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.cmbSpider = QtWidgets.QComboBox(self.tab_24)
        self.cmbSpider.setEnabled(False)
        self.cmbSpider.setObjectName("cmbSpider")
        self.cmbSpider.addItem("")
        self.cmbSpider.addItem("")
        self.cmbSpider.addItem("")
        self.cmbSpider.addItem("")
        self.cmbSpider.addItem("")
        self.cmbSpider.addItem("")
        self.cmbSpider.addItem("")
        self.cmbSpider.addItem("")
        self.cmbSpider.addItem("")
        self.cmbSpider.addItem("")
        self.horizontalLayout_10.addWidget(self.cmbSpider)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.gridLayout_5.addLayout(self.horizontalLayout_10, 1, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.tab_24)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 5, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_24)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_29 = QtWidgets.QWidget()
        self.tab_29.setObjectName("tab_29")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_29)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.btnNewItem = QtWidgets.QPushButton(self.tab_29)
        self.btnNewItem.setMinimumSize(QtCore.QSize(75, 0))
        self.btnNewItem.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnNewItem.setObjectName("btnNewItem")
        self.gridLayout_6.addWidget(self.btnNewItem, 0, 2, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.tab_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_6.addWidget(self.listWidget, 3, 0, 1, 3)
        self.label_27 = QtWidgets.QLabel(self.tab_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(50, 0))
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 0, 0, 1, 1)
        self.ledBookname = QtWidgets.QLineEdit(self.tab_29)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledBookname.sizePolicy().hasHeightForWidth())
        self.ledBookname.setSizePolicy(sizePolicy)
        self.ledBookname.setObjectName("ledBookname")
        self.gridLayout_6.addWidget(self.ledBookname, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 3, 3, 1, 1)
        self.tabWidget_2.addTab(self.tab_29, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.btnNewParams = QtWidgets.QPushButton(self.tab)
        self.btnNewParams.setMinimumSize(QtCore.QSize(75, 0))
        self.btnNewParams.setMaximumSize(QtCore.QSize(75, 16777215))
        self.btnNewParams.setObjectName("btnNewParams")
        self.gridLayout_7.addWidget(self.btnNewParams, 0, 0, 1, 1)
        self.tableStartParams = QtWidgets.QTableWidget(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableStartParams.sizePolicy().hasHeightForWidth())
        self.tableStartParams.setSizePolicy(sizePolicy)
        self.tableStartParams.setObjectName("tableStartParams")
        self.tableStartParams.setColumnCount(4)
        self.tableStartParams.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableStartParams.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStartParams.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStartParams.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStartParams.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableStartParams.setHorizontalHeaderItem(3, item)
        self.gridLayout_7.addWidget(self.tableStartParams, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem7, 1, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab, "")
        self.gridLayout_5.addWidget(self.tabWidget_2, 4, 3, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_24)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 0, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_24)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_12.addWidget(self.lineEdit_10)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem8)
        self.gridLayout_5.addLayout(self.horizontalLayout_12, 0, 3, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.tab_24)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 2, 0, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.tab_24)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 3, 0, 1, 1)
        self.lbDescription = QtWidgets.QLabel(self.tab_24)
        self.lbDescription.setObjectName("lbDescription")
        self.gridLayout_5.addWidget(self.lbDescription, 3, 3, 1, 1)
        self.tabProject.addTab(self.tab_24, "")
        self.tab_14 = QtWidgets.QWidget()
        self.tab_14.setObjectName("tab_14")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_14)
        self.tabWidget_3.setGeometry(QtCore.QRect(10, 30, 861, 425))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_3.sizePolicy().hasHeightForWidth())
        self.tabWidget_3.setSizePolicy(sizePolicy)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_11)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.radioButton = QtWidgets.QRadioButton(self.tab_11)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_3.addWidget(self.radioButton, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.tab_11)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_11)
        self.radioButton_7.setObjectName("radioButton_7")
        self.gridLayout_3.addWidget(self.radioButton_7, 1, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_11)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout_3.addWidget(self.radioButton_4, 1, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ledJobdir = QtWidgets.QLineEdit(self.tab_11)
        self.ledJobdir.setObjectName("ledJobdir")
        self.horizontalLayout_3.addWidget(self.ledJobdir)
        self.btnJobdir = QtWidgets.QPushButton(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnJobdir.sizePolicy().hasHeightForWidth())
        self.btnJobdir.setSizePolicy(sizePolicy)
        self.btnJobdir.setMaximumSize(QtCore.QSize(25, 25))
        self.btnJobdir.setObjectName("btnJobdir")
        self.horizontalLayout_3.addWidget(self.btnJobdir)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 5, 1, 1, 3)
        self.label_2 = QtWidgets.QLabel(self.tab_11)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ledProjectpath = QtWidgets.QLineEdit(self.tab_11)
        self.ledProjectpath.setObjectName("ledProjectpath")
        self.horizontalLayout_4.addWidget(self.ledProjectpath)
        self.btnProjectpath = QtWidgets.QPushButton(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnProjectpath.sizePolicy().hasHeightForWidth())
        self.btnProjectpath.setSizePolicy(sizePolicy)
        self.btnProjectpath.setMaximumSize(QtCore.QSize(25, 25))
        self.btnProjectpath.setObjectName("btnProjectpath")
        self.horizontalLayout_4.addWidget(self.btnProjectpath)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 3, 1, 1, 3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_11)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_3.addWidget(self.radioButton_2, 0, 3, 1, 1)
        self.chbAddScratch = QtWidgets.QCheckBox(self.tab_11)
        self.chbAddScratch.setObjectName("chbAddScratch")
        self.gridLayout_3.addWidget(self.chbAddScratch, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_11)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ledImagedir = QtWidgets.QLineEdit(self.tab_11)
        self.ledImagedir.setObjectName("ledImagedir")
        self.horizontalLayout_2.addWidget(self.ledImagedir)
        self.btnImagedir = QtWidgets.QPushButton(self.tab_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImagedir.sizePolicy().hasHeightForWidth())
        self.btnImagedir.setSizePolicy(sizePolicy)
        self.btnImagedir.setMaximumSize(QtCore.QSize(25, 25))
        self.btnImagedir.setObjectName("btnImagedir")
        self.horizontalLayout_2.addWidget(self.btnImagedir)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 4, 1, 1, 3)
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_11)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_3.addWidget(self.radioButton_3, 0, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem9, 6, 1, 1, 1)
        self.tabWidget_3.addTab(self.tab_11, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_12)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_13 = QtWidgets.QLabel(self.tab_12)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.tab_12)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 4, 0, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_4.addWidget(self.lineEdit_7, 5, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_4.addWidget(self.lineEdit_5, 2, 1, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_4.addWidget(self.lineEdit_6, 4, 1, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.tab_12)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_4.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.tab_12)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_4.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.tab_12)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_4.addWidget(self.checkBox, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_4.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.tab_12)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 6, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.tab_12)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_4.addWidget(self.checkBox_6, 6, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem10, 7, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_12, "")
        self.tab_13 = QtWidgets.QWidget()
        self.tab_13.setObjectName("tab_13")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_13)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.spbMaxPage = QtWidgets.QSpinBox(self.tab_13)
        self.spbMaxPage.setObjectName("spbMaxPage")
        self.gridLayout.addWidget(self.spbMaxPage, 3, 1, 1, 1)
        self.chkMaxTime = QtWidgets.QCheckBox(self.tab_13)
        self.chkMaxTime.setObjectName("chkMaxTime")
        self.gridLayout.addWidget(self.chkMaxTime, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spbMaxTime = QtWidgets.QSpinBox(self.tab_13)
        self.spbMaxTime.setMaximum(86400)
        self.spbMaxTime.setSingleStep(300)
        self.spbMaxTime.setObjectName("spbMaxTime")
        self.gridLayout.addWidget(self.spbMaxTime, 2, 1, 1, 1)
        self.chkMaxItem = QtWidgets.QCheckBox(self.tab_13)
        self.chkMaxItem.setObjectName("chkMaxItem")
        self.gridLayout.addWidget(self.chkMaxItem, 1, 0, 1, 1)
        self.chkMaxPage = QtWidgets.QCheckBox(self.tab_13)
        self.chkMaxPage.setObjectName("chkMaxPage")
        self.gridLayout.addWidget(self.chkMaxPage, 3, 0, 1, 1)
        self.spbMaxItem = QtWidgets.QSpinBox(self.tab_13)
        self.spbMaxItem.setObjectName("spbMaxItem")
        self.gridLayout.addWidget(self.spbMaxItem, 1, 1, 1, 1)
        self.spbMaxDepth = QtWidgets.QSpinBox(self.tab_13)
        self.spbMaxDepth.setObjectName("spbMaxDepth")
        self.gridLayout.addWidget(self.spbMaxDepth, 5, 1, 1, 1)
        self.spbMaxDepthWeight = QtWidgets.QSpinBox(self.tab_13)
        self.spbMaxDepthWeight.setMinimum(-99)
        self.spbMaxDepthWeight.setObjectName("spbMaxDepthWeight")
        self.gridLayout.addWidget(self.spbMaxDepthWeight, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_13)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.tab_13)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 5, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.tab_13)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 6, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem11, 7, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_13, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.label_8 = QtWidgets.QLabel(self.tab_10)
        self.label_8.setGeometry(QtCore.QRect(20, 40, 54, 12))
        self.label_8.setObjectName("label_8")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_4.setGeometry(QtCore.QRect(100, 40, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.tab_10)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 54, 12))
        self.label_7.setObjectName("label_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 10, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_10)
        self.radioButton_6.setGeometry(QtCore.QRect(100, 110, 47, 16))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_10)
        self.radioButton_5.setGeometry(QtCore.QRect(100, 80, 71, 16))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_8 = QtWidgets.QRadioButton(self.tab_10)
        self.radioButton_8.setGeometry(QtCore.QRect(180, 80, 53, 16))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_11 = QtWidgets.QRadioButton(self.tab_10)
        self.radioButton_11.setGeometry(QtCore.QRect(260, 80, 53, 16))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.tab_10)
        self.radioButton_12.setGeometry(QtCore.QRect(180, 110, 81, 16))
        self.radioButton_12.setObjectName("radioButton_12")
        self.label_26 = QtWidgets.QLabel(self.tab_10)
        self.label_26.setGeometry(QtCore.QRect(10, 80, 72, 15))
        self.label_26.setObjectName("label_26")
        self.tabWidget_3.addTab(self.tab_10, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.checkBox_4 = QtWidgets.QCheckBox(self.tab_21)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 200, 119, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.chkLogEnable = QtWidgets.QCheckBox(self.tab_21)
        self.chkLogEnable.setGeometry(QtCore.QRect(15, 62, 119, 16))
        self.chkLogEnable.setObjectName("chkLogEnable")
        self.cmbLogLevel = QtWidgets.QComboBox(self.tab_21)
        self.cmbLogLevel.setGeometry(QtCore.QRect(140, 60, 133, 20))
        self.cmbLogLevel.setObjectName("cmbLogLevel")
        self.cmbLogLevel.addItem("")
        self.cmbLogLevel.addItem("")
        self.cmbLogLevel.addItem("")
        self.cmbLogLevel.addItem("")
        self.cmbLogLevel.addItem("")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.tab_21)
        self.dateTimeEdit.setGeometry(QtCore.QRect(80, 140, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.label_10 = QtWidgets.QLabel(self.tab_21)
        self.label_10.setGeometry(QtCore.QRect(10, 140, 54, 12))
        self.label_10.setObjectName("label_10")
        self.ledLogFile = QtWidgets.QLineEdit(self.tab_21)
        self.ledLogFile.setGeometry(QtCore.QRect(140, 90, 121, 21))
        self.ledLogFile.setObjectName("ledLogFile")
        self.chkLogStdout = QtWidgets.QCheckBox(self.tab_21)
        self.chkLogStdout.setGeometry(QtCore.QRect(20, 90, 71, 16))
        self.chkLogStdout.setObjectName("chkLogStdout")
        self.checkBox_10 = QtWidgets.QCheckBox(self.tab_21)
        self.checkBox_10.setGeometry(QtCore.QRect(20, 180, 119, 16))
        self.checkBox_10.setObjectName("checkBox_10")
        self.tabWidget_3.addTab(self.tab_21, "")
        self.tab_22 = QtWidgets.QWidget()
        self.tab_22.setObjectName("tab_22")
        self.label_14 = QtWidgets.QLabel(self.tab_22)
        self.label_14.setGeometry(QtCore.QRect(20, 70, 81, 16))
        self.label_14.setObjectName("label_14")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.tab_22)
        self.doubleSpinBox.setGeometry(QtCore.QRect(150, 60, 62, 22))
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.checkBox_8 = QtWidgets.QCheckBox(self.tab_22)
        self.checkBox_8.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.checkBox_8.setObjectName("checkBox_8")
        self.label_15 = QtWidgets.QLabel(self.tab_22)
        self.label_15.setGeometry(QtCore.QRect(20, 100, 81, 16))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.checkBox_9 = QtWidgets.QCheckBox(self.tab_22)
        self.checkBox_9.setGeometry(QtCore.QRect(150, 100, 71, 16))
        self.checkBox_9.setObjectName("checkBox_9")
        self.label_16 = QtWidgets.QLabel(self.tab_22)
        self.label_16.setGeometry(QtCore.QRect(30, 140, 81, 16))
        self.label_16.setObjectName("label_16")
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.tab_22)
        self.doubleSpinBox_2.setGeometry(QtCore.QRect(140, 130, 62, 22))
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.spinBox = QtWidgets.QSpinBox(self.tab_22)
        self.spinBox.setGeometry(QtCore.QRect(160, 160, 42, 22))
        self.spinBox.setProperty("value", 32)
        self.spinBox.setObjectName("spinBox")
        self.label_17 = QtWidgets.QLabel(self.tab_22)
        self.label_17.setGeometry(QtCore.QRect(30, 170, 81, 16))
        self.label_17.setObjectName("label_17")
        self.radioButton_9 = QtWidgets.QRadioButton(self.tab_22)
        self.radioButton_9.setGeometry(QtCore.QRect(20, 200, 89, 16))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.tab_22)
        self.radioButton_10.setGeometry(QtCore.QRect(110, 200, 89, 16))
        self.radioButton_10.setObjectName("radioButton_10")
        self.tabWidget_3.addTab(self.tab_22, "")
        self.tabProject.addTab(self.tab_14, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.btnImportConfig = QtWidgets.QPushButton(self.tab_4)
        self.btnImportConfig.setObjectName("btnImportConfig")
        self.horizontalLayout_6.addWidget(self.btnImportConfig)
        self.btnExportConfig = QtWidgets.QPushButton(self.tab_4)
        self.btnExportConfig.setObjectName("btnExportConfig")
        self.horizontalLayout_6.addWidget(self.btnExportConfig)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.txtConfig = QtWidgets.QTextEdit(self.tab_4)
        self.txtConfig.setObjectName("txtConfig")
        self.verticalLayout_5.addWidget(self.txtConfig)
        self.tabProject.addTab(self.tab_4, "")
        self.stackedWidget.addWidget(self.tabProject)
        self.tabRunning = QtWidgets.QTabWidget()
        self.tabRunning.setObjectName("tabRunning")
        self.tab_31 = QtWidgets.QWidget()
        self.tab_31.setObjectName("tab_31")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.tab_31)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_31)
        self.textBrowser.setMinimumSize(QtCore.QSize(400, 0))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_8.addWidget(self.textBrowser)
        self.textEdit = QtWidgets.QTextEdit(self.tab_31)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 80))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_8.addWidget(self.textEdit)
        self.tabRunning.addTab(self.tab_31, "")
        self.tab_32 = QtWidgets.QWidget()
        self.tab_32.setObjectName("tab_32")
        self.treeView = QtWidgets.QTreeView(self.tab_32)
        self.treeView.setGeometry(QtCore.QRect(10, 10, 757, 499))
        self.treeView.setObjectName("treeView")
        self.tabRunning.addTab(self.tab_32, "")
        self.stackedWidget.addWidget(self.tabRunning)
        self.tabWidget_4 = QtWidgets.QTabWidget()
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_27 = QtWidgets.QWidget()
        self.tab_27.setObjectName("tab_27")
        self.tabCategory = QtWidgets.QTabWidget(self.tab_27)
        self.tabCategory.setGeometry(QtCore.QRect(50, 270, 272, 44))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabCategory.sizePolicy().hasHeightForWidth())
        self.tabCategory.setSizePolicy(sizePolicy)
        self.tabCategory.setMaximumSize(QtCore.QSize(322, 44))
        self.tabCategory.setObjectName("tabCategory")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabCategory.addTab(self.tab_2, "")
        self.tab_23 = QtWidgets.QWidget()
        self.tab_23.setObjectName("tab_23")
        self.tabCategory.addTab(self.tab_23, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabCategory.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabCategory.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabCategory.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabCategory.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabCategory.addTab(self.tab_9, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.tabCategory.addTab(self.tab_15, "")
        self.tab_16 = QtWidgets.QWidget()
        self.tab_16.setObjectName("tab_16")
        self.tabCategory.addTab(self.tab_16, "")
        self.tab_17 = QtWidgets.QWidget()
        self.tab_17.setObjectName("tab_17")
        self.tabCategory.addTab(self.tab_17, "")
        self.tab_18 = QtWidgets.QWidget()
        self.tab_18.setObjectName("tab_18")
        self.tabCategory.addTab(self.tab_18, "")
        self.tab_19 = QtWidgets.QWidget()
        self.tab_19.setObjectName("tab_19")
        self.tabCategory.addTab(self.tab_19, "")
        self.tab_20 = QtWidgets.QWidget()
        self.tab_20.setObjectName("tab_20")
        self.tabCategory.addTab(self.tab_20, "")
        self.label_6 = QtWidgets.QLabel(self.tab_27)
        self.label_6.setGeometry(QtCore.QRect(50, 60, 151, 16))
        self.label_6.setObjectName("label_6")
        self.ledRunstring = QtWidgets.QLineEdit(self.tab_27)
        self.ledRunstring.setGeometry(QtCore.QRect(220, 120, 221, 41))
        self.ledRunstring.setObjectName("ledRunstring")
        self.btnRun = QtWidgets.QPushButton(self.tab_27)
        self.btnRun.setGeometry(QtCore.QRect(510, 230, 81, 51))
        self.btnRun.setObjectName("btnRun")
        self.btnTmp2 = QtWidgets.QPushButton(self.tab_27)
        self.btnTmp2.setGeometry(QtCore.QRect(580, 200, 75, 23))
        self.btnTmp2.setObjectName("btnTmp2")
        self.btnTmp = QtWidgets.QPushButton(self.tab_27)
        self.btnTmp.setGeometry(QtCore.QRect(580, 160, 75, 23))
        self.btnTmp.setObjectName("btnTmp")
        self.tabWidget_4.addTab(self.tab_27, "")
        self.tab_33 = QtWidgets.QWidget()
        self.tab_33.setObjectName("tab_33")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_33)
        self.lineEdit_8.setGeometry(QtCore.QRect(130, 55, 657, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_33)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 52, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.btnViewUrl = QtWidgets.QPushButton(self.tab_33)
        self.btnViewUrl.setGeometry(QtCore.QRect(10, 17, 93, 28))
        self.btnViewUrl.setObjectName("btnViewUrl")
        self.wdgWeb = QtWidgets.QWidget(self.tab_33)
        self.wdgWeb.setGeometry(QtCore.QRect(30, 87, 757, 429))
        self.wdgWeb.setObjectName("wdgWeb")
        self.ledViewUrl = QtWidgets.QLineEdit(self.tab_33)
        self.ledViewUrl.setGeometry(QtCore.QRect(130, 20, 657, 21))
        self.ledViewUrl.setObjectName("ledViewUrl")
        self.tabWidget_4.addTab(self.tab_33, "")
        self.stackedWidget.addWidget(self.tabWidget_4)
        self.tabExport = QtWidgets.QTabWidget()
        self.tabExport.setObjectName("tabExport")
        self.tab_25 = QtWidgets.QWidget()
        self.tab_25.setObjectName("tab_25")
        self.pushButton = QtWidgets.QPushButton(self.tab_25)
        self.pushButton.setGeometry(QtCore.QRect(120, 60, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.tabExport.addTab(self.tab_25, "")
        self.tab_26 = QtWidgets.QWidget()
        self.tab_26.setObjectName("tab_26")
        self.tabExport.addTab(self.tab_26, "")
        self.stackedWidget.addWidget(self.tabExport)
        self.verticalLayout_9.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1076, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        self.label_4 = QtWidgets.QLabel(self.statusBar)
        self.label_4.setGeometry(QtCore.QRect(35, 0, 72, 20))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.lbTime = QtWidgets.QLabel(self.statusBar)
        self.lbTime.setGeometry(QtCore.QRect(150, 0, 160, 20))
        self.lbTime.setObjectName("lbTime")
        self.btnShowTab = QtWidgets.QPushButton(self.statusBar)
        self.btnShowTab.setGeometry(QtCore.QRect(5, -5, 25, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnShowTab.sizePolicy().hasHeightForWidth())
        self.btnShowTab.setSizePolicy(sizePolicy)
        self.btnShowTab.setCheckable(True)
        self.btnShowTab.setFlat(True)
        self.btnShowTab.setObjectName("btnShowTab")
        self.progressBar = QtWidgets.QProgressBar(self.statusBar)
        self.progressBar.setGeometry(QtCore.QRect(420, 0, 118, 20))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/开始_dis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/stop_326px_1187740_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon1)
        self.actionStop.setObjectName("actionStop")
        self.actionClear = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/editclear_128px_32658_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon2)
        self.actionClear.setObjectName("actionClear")
        self.actionNewProj = QtWidgets.QAction(MainWindow)
        self.actionNewProj.setObjectName("actionNewProj")
        self.actionOpenProj = QtWidgets.QAction(MainWindow)
        self.actionOpenProj.setObjectName("actionOpenProj")
        self.actionPreferer = QtWidgets.QAction(MainWindow)
        self.actionPreferer.setObjectName("actionPreferer")
        self.actionRecent = QtWidgets.QAction(MainWindow)
        self.actionRecent.setObjectName("actionRecent")
        self.actionfuvi = QtWidgets.QAction(MainWindow)
        self.actionfuvi.setObjectName("actionfuvi")
        self.actionnmtx = QtWidgets.QAction(MainWindow)
        self.actionnmtx.setObjectName("actionnmtx")
        self.actionNewWizard = QtWidgets.QAction(MainWindow)
        self.actionNewWizard.setObjectName("actionNewWizard")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionSaveas = QtWidgets.QAction(MainWindow)
        self.actionSaveas.setObjectName("actionSaveas")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionNewItem = QtWidgets.QAction(MainWindow)
        self.actionNewItem.setObjectName("actionNewItem")
        self.actionDeleteItem = QtWidgets.QAction(MainWindow)
        self.actionDeleteItem.setObjectName("actionDeleteItem")
        self.actionClearItems = QtWidgets.QAction(MainWindow)
        self.actionClearItems.setObjectName("actionClearItems")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setEnabled(False)
        self.actionPause.setObjectName("actionPause")
        self.menu.addAction(self.actionNewProj)
        self.menu.addAction(self.actionNewWizard)
        self.menu.addAction(self.actionOpenProj)
        self.menu.addAction(self.actionSave)
        self.menu.addAction(self.actionSaveas)
        self.menu.addAction(self.actionRecent)
        self.menu.addAction(self.actionPreferer)
        self.menu_2.addAction(self.actionfuvi)
        self.menu_2.addAction(self.actionnmtx)
        self.menu_5.addAction(self.actionAbout)
        self.menu_5.addAction(self.actionHelp)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())
        self.mainToolBar.addAction(self.actionNewProj)
        self.mainToolBar.addAction(self.actionOpenProj)
        self.mainToolBar.addAction(self.actionSave)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionStart)
        self.mainToolBar.addAction(self.actionStop)
        self.mainToolBar.addAction(self.actionPause)
        self.mainToolBar.addAction(self.actionClear)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.tabProject.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(2)
        self.tabRunning.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.tabCategory.setCurrentIndex(8)
        self.tabExport.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnProjectTab.setText(_translate("MainWindow", "项目"))
        self.btnRunningTab.setText(_translate("MainWindow", "运行"))
        self.btnCustomTab.setText(_translate("MainWindow", "定制"))
        self.btnExportTab.setText(_translate("MainWindow", "导出"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("MainWindow", "recent"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.btnJumpTemplate.setText(_translate("MainWindow", "立即使用"))
        self.label_5.setText(_translate("MainWindow", "简易采集"))
        self.label_21.setText(_translate("MainWindow", "内置主流网站，一键配置"))
        self.label_45.setText(_translate("MainWindow", "自由配置，适应所有场景"))
        self.label_46.setText(_translate("MainWindow", "自定义采集"))
        self.btnJumpCutom.setText(_translate("MainWindow", "立即使用"))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tab_30), _translate("MainWindow", "起始页"))
        self.cmbTagFilter.setItemText(0, _translate("MainWindow", "全部"))
        self.cmbTagFilter.setItemText(1, _translate("MainWindow", "图片"))
        self.cmbTagFilter.setItemText(2, _translate("MainWindow", "漫画"))
        self.cmbTagFilter.setItemText(3, _translate("MainWindow", "文档"))
        self.cmbTagFilter.setItemText(4, _translate("MainWindow", "BBS"))
        self.cmbTagFilter.setItemText(5, _translate("MainWindow", "资源"))
        self.cmbTagFilter.setItemText(6, _translate("MainWindow", "电商"))
        self.cmbTagFilter.setItemText(7, _translate("MainWindow", "财经"))
        self.cmbTagFilter.setItemText(8, _translate("MainWindow", "工具"))
        self.cmbTagFilter.setItemText(9, _translate("MainWindow", "新闻"))
        self.ledKeyword.setPlaceholderText(_translate("MainWindow", "search spider"))
        self.lbSpider.setText(_translate("MainWindow", "dmzj"))
        self.btnGotoTemplate.setText(_translate("MainWindow", "goto"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "爬虫"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "类别"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "网址"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "描述"))
        self.btnNewSpider.setText(_translate("MainWindow", "添加"))
        self.btnSaveSpiderTable.setText(_translate("MainWindow", "保存"))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tab_28), _translate("MainWindow", "模板页"))
        self.lbBaseurl.setText(_translate("MainWindow", "https://manhua.dmzj.com/"))
        self.pushButton_3.setText(_translate("MainWindow", "..."))
        self.label_20.setText(_translate("MainWindow", "模板"))
        self.label_24.setText(_translate("MainWindow", "\n"
"起始网址"))
        self.cmbSpider.setItemText(0, _translate("MainWindow", "dmzj"))
        self.cmbSpider.setItemText(1, _translate("MainWindow", "meizitu0"))
        self.cmbSpider.setItemText(2, _translate("MainWindow", "sgacg"))
        self.cmbSpider.setItemText(3, _translate("MainWindow", "acqq"))
        self.cmbSpider.setItemText(4, _translate("MainWindow", "mzitu"))
        self.cmbSpider.setItemText(5, _translate("MainWindow", "mm131"))
        self.cmbSpider.setItemText(6, _translate("MainWindow", "meizitu"))
        self.cmbSpider.setItemText(7, _translate("MainWindow", "doc_scrapy"))
        self.cmbSpider.setItemText(8, _translate("MainWindow", "baiduimage"))
        self.cmbSpider.setItemText(9, _translate("MainWindow", "23us"))
        self.label_25.setText(_translate("MainWindow", "输出路径"))
        self.btnNewItem.setText(_translate("MainWindow", "添加"))
        self.listWidget.setToolTip(_translate("MainWindow", "右键添加起始网页链接列表"))
        self.label_27.setText(_translate("MainWindow", "网页"))
        self.ledBookname.setToolTip(_translate("MainWindow", "输入书名拼音，多本书使用分号间隔"))
        self.ledBookname.setPlaceholderText(_translate("MainWindow", "https://manhua.dmzj.com/yaojingdeweiba"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_29), _translate("MainWindow", "页地址"))
        self.btnNewParams.setText(_translate("MainWindow", "添加"))
        item = self.tableStartParams.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableStartParams.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "起始页"))
        item = self.tableStartParams.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "关键字"))
        item = self.tableStartParams.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "起始页码"))
        item = self.tableStartParams.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "翻页数"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "页参数"))
        self.label_23.setText(_translate("MainWindow", "名字"))
        self.label_28.setText(_translate("MainWindow", "域名"))
        self.label_29.setText(_translate("MainWindow", "描述"))
        self.lbDescription.setText(_translate("MainWindow", "动漫之家漫画网站"))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tab_24), _translate("MainWindow", "配置"))
        self.radioButton.setText(_translate("MainWindow", "CSV"))
        self.label_9.setText(_translate("MainWindow", "导出格式"))
        self.radioButton_7.setText(_translate("MainWindow", "xml"))
        self.radioButton_4.setText(_translate("MainWindow", "xls"))
        self.ledJobdir.setPlaceholderText(_translate("MainWindow", "jobdir"))
        self.btnJobdir.setText(_translate("MainWindow", "..."))
        self.label_2.setText(_translate("MainWindow", "项目路径"))
        self.ledProjectpath.setPlaceholderText(_translate("MainWindow", "project"))
        self.btnProjectpath.setText(_translate("MainWindow", "..."))
        self.radioButton_2.setText(_translate("MainWindow", "JSONLINE"))
        self.chbAddScratch.setText(_translate("MainWindow", "增量抓取"))
        self.label_3.setText(_translate("MainWindow", "图片路径"))
        self.ledImagedir.setPlaceholderText(_translate("MainWindow", "images"))
        self.btnImagedir.setText(_translate("MainWindow", "..."))
        self.radioButton_3.setText(_translate("MainWindow", "json"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_11), _translate("MainWindow", "导出"))
        self.label_13.setText(_translate("MainWindow", "密码"))
        self.label_12.setText(_translate("MainWindow", "账号"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "******"))
        self.lineEdit_5.setPlaceholderText(_translate("MainWindow", "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36"))
        self.checkBox_3.setText(_translate("MainWindow", "启用账号密码登录"))
        self.checkBox_2.setText(_translate("MainWindow", "UserAgent"))
        self.checkBox.setText(_translate("MainWindow", "proxy"))
        self.checkBox_6.setText(_translate("MainWindow", "cookie"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_12), _translate("MainWindow", "登录"))
        self.chkMaxTime.setText(_translate("MainWindow", "最长时间(秒)"))
        self.label.setText(_translate("MainWindow", "停止条件"))
        self.chkMaxItem.setText(_translate("MainWindow", "最多物件"))
        self.chkMaxPage.setText(_translate("MainWindow", "最多页面"))
        self.spbMaxDepth.setToolTip(_translate("MainWindow", "<html><head/><body><p>限制网页最大深度，<span style=\" font-weight:600;\">（0为没有限制）</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "调度策略"))
        self.label_18.setToolTip(_translate("MainWindow", "<html><head/><body><p>限制网页最大深度，<span style=\" font-weight:600;\">（0为没有限制）</span></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "最大深度限制"))
        self.label_19.setToolTip(_translate("MainWindow", "<html><head/><body><p>取值可正可负，越大对应<span style=\" font-weight:600;\">广度优先</span>；越小对应<span style=\" font-weight:600;\">深度优先</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "深度惩罚权重"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_13), _translate("MainWindow", "停止"))
        self.label_8.setText(_translate("MainWindow", "password"))
        self.label_7.setText(_translate("MainWindow", "hostname"))
        self.radioButton_6.setText(_translate("MainWindow", "sql"))
        self.radioButton_5.setText(_translate("MainWindow", "mongo"))
        self.radioButton_8.setText(_translate("MainWindow", "redis"))
        self.radioButton_11.setText(_translate("MainWindow", "sqlite"))
        self.radioButton_12.setText(_translate("MainWindow", "postgres"))
        self.label_26.setText(_translate("MainWindow", "数据库"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_10), _translate("MainWindow", "数据库"))
        self.checkBox_4.setText(_translate("MainWindow", "调试模式"))
        self.chkLogEnable.setText(_translate("MainWindow", "启用记录"))
        self.cmbLogLevel.setItemText(0, _translate("MainWindow", "DEBUG"))
        self.cmbLogLevel.setItemText(1, _translate("MainWindow", "INFO"))
        self.cmbLogLevel.setItemText(2, _translate("MainWindow", "WARNING"))
        self.cmbLogLevel.setItemText(3, _translate("MainWindow", "ERROR"))
        self.cmbLogLevel.setItemText(4, _translate("MainWindow", "CRITICAL"))
        self.label_10.setText(_translate("MainWindow", "定时任务"))
        self.ledLogFile.setPlaceholderText(_translate("MainWindow", "scrapy.log"))
        self.chkLogStdout.setText(_translate("MainWindow", "文件输出"))
        self.checkBox_10.setText(_translate("MainWindow", "telnet启用"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_21), _translate("MainWindow", "杂类"))
        self.label_14.setText(_translate("MainWindow", "下载延迟(秒)"))
        self.checkBox_8.setText(_translate("MainWindow", "限速"))
        self.checkBox_9.setText(_translate("MainWindow", "随机延迟"))
        self.label_16.setText(_translate("MainWindow", "自动限速"))
        self.label_17.setText(_translate("MainWindow", "最大并发请求数量"))
        self.radioButton_9.setText(_translate("MainWindow", "DFO"))
        self.radioButton_10.setText(_translate("MainWindow", "BFO"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_22), _translate("MainWindow", "限速"))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tab_14), _translate("MainWindow", "其他"))
        self.btnImportConfig.setText(_translate("MainWindow", "导入"))
        self.btnExportConfig.setText(_translate("MainWindow", "导出"))
        self.tabProject.setTabText(self.tabProject.indexOf(self.tab_4), _translate("MainWindow", "代码配置"))
        self.tabRunning.setTabText(self.tabRunning.indexOf(self.tab_31), _translate("MainWindow", "记录"))
        self.tabRunning.setTabText(self.tabRunning.indexOf(self.tab_32), _translate("MainWindow", "目录"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_2), _translate("MainWindow", "全部"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_23), _translate("MainWindow", "图片"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_5), _translate("MainWindow", "漫画"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_6), _translate("MainWindow", "文档"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_7), _translate("MainWindow", "BBS"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_8), _translate("MainWindow", "新闻"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_9), _translate("MainWindow", "视频"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_15), _translate("MainWindow", "信息"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_16), _translate("MainWindow", "音乐"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_17), _translate("MainWindow", "小说"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_18), _translate("MainWindow", "电商"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_19), _translate("MainWindow", "财经"))
        self.tabCategory.setTabText(self.tabCategory.indexOf(self.tab_20), _translate("MainWindow", "游戏"))
        self.label_6.setText(_translate("MainWindow", "测试工具，验证码识别"))
        self.btnRun.setText(_translate("MainWindow", "run"))
        self.btnTmp2.setText(_translate("MainWindow", "tmp2"))
        self.btnTmp.setText(_translate("MainWindow", "tmp"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_27), _translate("MainWindow", "调试"))
        self.pushButton_2.setText(_translate("MainWindow", "xpath"))
        self.btnViewUrl.setText(_translate("MainWindow", "view"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_33), _translate("MainWindow", "web页"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.tabExport.setTabText(self.tabExport.indexOf(self.tab_25), _translate("MainWindow", "Tab 1"))
        self.tabExport.setTabText(self.tabExport.indexOf(self.tab_26), _translate("MainWindow", "Tab 2"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "视图"))
        self.menu_4.setTitle(_translate("MainWindow", "工具"))
        self.menu_5.setTitle(_translate("MainWindow", "帮助"))
        self.lbTime.setText(_translate("MainWindow", "2019/11/11 18:30:31"))
        self.btnShowTab.setText(_translate("MainWindow", "..."))
        self.actionStart.setText(_translate("MainWindow", "开始"))
        self.actionStart.setShortcut(_translate("MainWindow", "F5"))
        self.actionStop.setText(_translate("MainWindow", "停止"))
        self.actionStop.setShortcut(_translate("MainWindow", "Shift+F5"))
        self.actionClear.setText(_translate("MainWindow", "清除"))
        self.actionNewProj.setText(_translate("MainWindow", "新建"))
        self.actionOpenProj.setText(_translate("MainWindow", "打开"))
        self.actionPreferer.setText(_translate("MainWindow", "偏好"))
        self.actionRecent.setText(_translate("MainWindow", "最近访问项目"))
        self.actionfuvi.setText(_translate("MainWindow", "复制"))
        self.actionnmtx.setText(_translate("MainWindow", "黏贴"))
        self.actionNewWizard.setText(_translate("MainWindow", "新建项目(指引)"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
        self.actionAbout.setToolTip(_translate("MainWindow", "关于"))
        self.actionHelp.setText(_translate("MainWindow", "帮助"))
        self.actionHelp.setToolTip(_translate("MainWindow", "帮助"))
        self.actionSaveas.setText(_translate("MainWindow", "另存为"))
        self.actionSave.setText(_translate("MainWindow", "保存"))
        self.actionNewItem.setText(_translate("MainWindow", "新建列表项"))
        self.actionDeleteItem.setText(_translate("MainWindow", "删除列表项"))
        self.actionClearItems.setText(_translate("MainWindow", "清除列表项"))
        self.actionPause.setText(_translate("MainWindow", "暂停"))

import pyscr_rc
