# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1022, 664)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(322, 44))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_2.addTab(self.tab_2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_2.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_2.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.tabWidget_2.addTab(self.tab_9, "")
        self.verticalLayout_2.addWidget(self.tabWidget_2)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.chkMaxTime = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkMaxTime.setObjectName("chkMaxTime")
        self.gridLayout_2.addWidget(self.chkMaxTime, 5, 0, 1, 1)
        self.spbMaxTime = QtWidgets.QSpinBox(self.groupBox_2)
        self.spbMaxTime.setMaximum(86400)
        self.spbMaxTime.setSingleStep(300)
        self.spbMaxTime.setObjectName("spbMaxTime")
        self.gridLayout_2.addWidget(self.spbMaxTime, 5, 1, 1, 1)
        self.ledBookname = QtWidgets.QLineEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledBookname.sizePolicy().hasHeightForWidth())
        self.ledBookname.setSizePolicy(sizePolicy)
        self.ledBookname.setObjectName("ledBookname")
        self.gridLayout_2.addWidget(self.ledBookname, 3, 0, 1, 2)
        self.chkMaxItem = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkMaxItem.setObjectName("chkMaxItem")
        self.gridLayout_2.addWidget(self.chkMaxItem, 4, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.spbMaxItem = QtWidgets.QSpinBox(self.groupBox_2)
        self.spbMaxItem.setObjectName("spbMaxItem")
        self.gridLayout_2.addWidget(self.spbMaxItem, 4, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.chkMaxPage = QtWidgets.QCheckBox(self.groupBox_2)
        self.chkMaxPage.setObjectName("chkMaxPage")
        self.gridLayout_2.addWidget(self.chkMaxPage, 6, 0, 1, 1)
        self.spbMaxPage = QtWidgets.QSpinBox(self.groupBox_2)
        self.spbMaxPage.setObjectName("spbMaxPage")
        self.gridLayout_2.addWidget(self.spbMaxPage, 6, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 50, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 30, 54, 12))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(20, 50, 54, 12))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 0, 1, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout.addWidget(self.radioButton_3, 0, 3, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 4)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setObjectName("radioButton_5")
        self.gridLayout.addWidget(self.radioButton_5, 1, 0, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setObjectName("radioButton_4")
        self.gridLayout.addWidget(self.radioButton_4, 1, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 4)
        self.chbAddScratch = QtWidgets.QCheckBox(self.groupBox)
        self.chbAddScratch.setObjectName("chbAddScratch")
        self.gridLayout.addWidget(self.chbAddScratch, 3, 0, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_6.setObjectName("radioButton_6")
        self.gridLayout.addWidget(self.radioButton_6, 1, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(455, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget = QtWidgets.QWidget(self.tab_3)
        self.widget.setGeometry(QtCore.QRect(60, 70, 301, 191))
        self.widget.setObjectName("widget")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(30, 490, 72, 15))
        self.label_6.setObjectName("label_6")
        self.ledRunstring = QtWidgets.QLineEdit(self.tab_3)
        self.ledRunstring.setGeometry(QtCore.QRect(50, 340, 221, 41))
        self.ledRunstring.setObjectName("ledRunstring")
        self.btnRun = QtWidgets.QPushButton(self.tab_3)
        self.btnRun.setGeometry(QtCore.QRect(310, 330, 81, 51))
        self.btnRun.setObjectName("btnRun")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.txtConfig = QtWidgets.QTextEdit(self.tab)
        self.txtConfig.setGeometry(QtCore.QRect(10, 20, 421, 311))
        self.txtConfig.setObjectName("txtConfig")
        self.tabWidget.addTab(self.tab, "")
        self.textBrowser = QtWidgets.QTextBrowser(self.splitter)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1022, 26))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menuBar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menuBar)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menuBar)
        self.menu_5.setObjectName("menu_5")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        self.label_4 = QtWidgets.QLabel(self.statusBar)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.statusBar)
        self.label_5.setGeometry(QtCore.QRect(300, 0, 72, 15))
        self.label_5.setObjectName("label_5")
        self.progressBar = QtWidgets.QProgressBar(self.statusBar)
        self.progressBar.setGeometry(QtCore.QRect(420, 0, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionStart = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/开始_dis.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStart.setIcon(icon)
        self.actionStart.setObjectName("actionStart")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/stop_326px_1187740_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon1)
        self.actionStop.setObjectName("actionStop")
        self.actionClear = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/editclear_128px_32658_easyicon.net.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon2)
        self.actionClear.setObjectName("actionClear")
        self.actionNewProj = QtWidgets.QAction(MainWindow)
        self.actionNewProj.setObjectName("actionNewProj")
        self.actionOpenProj = QtWidgets.QAction(MainWindow)
        self.actionOpenProj.setObjectName("actionOpenProj")
        self.actionpzvi = QtWidgets.QAction(MainWindow)
        self.actionpzvi.setObjectName("actionpzvi")
        self.actionrecent = QtWidgets.QAction(MainWindow)
        self.actionrecent.setObjectName("actionrecent")
        self.actionfuvi = QtWidgets.QAction(MainWindow)
        self.actionfuvi.setObjectName("actionfuvi")
        self.actionnmtx = QtWidgets.QAction(MainWindow)
        self.actionnmtx.setObjectName("actionnmtx")
        self.actionNewWizard = QtWidgets.QAction(MainWindow)
        self.actionNewWizard.setObjectName("actionNewWizard")
        self.menu.addAction(self.actionNewProj)
        self.menu.addAction(self.actionNewWizard)
        self.menu.addAction(self.actionOpenProj)
        self.menu.addAction(self.actionrecent)
        self.menu.addAction(self.actionpzvi)
        self.menu_2.addAction(self.actionfuvi)
        self.menu_2.addAction(self.actionnmtx)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())
        self.menuBar.addAction(self.menu_3.menuAction())
        self.menuBar.addAction(self.menu_4.menuAction())
        self.menuBar.addAction(self.menu_5.menuAction())
        self.mainToolBar.addAction(self.actionStart)
        self.mainToolBar.addAction(self.actionStop)
        self.mainToolBar.addAction(self.actionClear)

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "页"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "漫画"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "文档"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_7), _translate("MainWindow", "BBS"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_8), _translate("MainWindow", "新闻"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "视频"))
        self.chkMaxTime.setText(_translate("MainWindow", "最长时间(秒)"))
        self.ledBookname.setToolTip(_translate("MainWindow", "输入书名拼音，多本书使用分号间隔"))
        self.ledBookname.setPlaceholderText(_translate("MainWindow", "https://manhua.dmzj.com/yaojingdeweiba"))
        self.chkMaxItem.setText(_translate("MainWindow", "最多物件"))
        self.comboBox.setItemText(0, _translate("MainWindow", "dmzj"))
        self.comboBox.setItemText(1, _translate("MainWindow", "meizitu0"))
        self.comboBox.setItemText(2, _translate("MainWindow", "sgacg"))
        self.comboBox.setItemText(3, _translate("MainWindow", "acqq"))
        self.comboBox.setItemText(4, _translate("MainWindow", "mzitu"))
        self.comboBox.setItemText(5, _translate("MainWindow", "mm131"))
        self.comboBox.setItemText(6, _translate("MainWindow", "meizitu"))
        self.label_2.setText(_translate("MainWindow", "https://manhua.dmzj.com/"))
        self.chkMaxPage.setText(_translate("MainWindow", "最多页面"))
        self.groupBox_3.setTitle(_translate("MainWindow", "SQL"))
        self.label_7.setText(_translate("MainWindow", "hostname"))
        self.label_8.setText(_translate("MainWindow", "password"))
        self.groupBox.setTitle(_translate("MainWindow", "导出设置"))
        self.radioButton_2.setText(_translate("MainWindow", "jl"))
        self.radioButton_3.setText(_translate("MainWindow", "json"))
        self.checkBox_4.setText(_translate("MainWindow", "调试模式"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "images"))
        self.label_3.setText(_translate("MainWindow", "导出路径"))
        self.radioButton.setText(_translate("MainWindow", "CSV"))
        self.radioButton_5.setText(_translate("MainWindow", "mongo"))
        self.radioButton_4.setText(_translate("MainWindow", "xls"))
        self.chbAddScratch.setText(_translate("MainWindow", "增量抓取"))
        self.radioButton_6.setText(_translate("MainWindow", "sql"))
        self.checkBox_5.setText(_translate("MainWindow", "记录模式"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.btnRun.setText(_translate("MainWindow", "run"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "命令行"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "表格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "配置"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑"))
        self.menu_3.setTitle(_translate("MainWindow", "视图"))
        self.menu_4.setTitle(_translate("MainWindow", "工具"))
        self.menu_5.setTitle(_translate("MainWindow", "帮助"))
        self.label_4.setText(_translate("MainWindow", "123456"))
        self.label_5.setText(_translate("MainWindow", "9789796"))
        self.actionStart.setText(_translate("MainWindow", "开始"))
        self.actionStart.setShortcut(_translate("MainWindow", "F5"))
        self.actionStop.setText(_translate("MainWindow", "停止"))
        self.actionStop.setShortcut(_translate("MainWindow", "Shift+F5"))
        self.actionClear.setText(_translate("MainWindow", "清除"))
        self.actionNewProj.setText(_translate("MainWindow", "新建项目"))
        self.actionOpenProj.setText(_translate("MainWindow", "打开"))
        self.actionpzvi.setText(_translate("MainWindow", "偏好"))
        self.actionrecent.setText(_translate("MainWindow", "recent"))
        self.actionfuvi.setText(_translate("MainWindow", "复制"))
        self.actionnmtx.setText(_translate("MainWindow", "黏贴"))
        self.actionNewWizard.setText(_translate("MainWindow", "新建项目(指引)"))

import pyscr_rc
